name: Reuse Deployment

on:
  workflow_call:
    inputs:
        MONGO_URI:
            description: 'MongoDB Connection URI'
            required: true
            type: string
        KUBECTL-VERSION:
            description: 'kubectl version to install'
            required: false
            type: string
            default: 'v1.36.1'
        K8S-MENIFEST-DIR:
            description: 'Kubernetes manifest directory'
            required: true
            type: string
            default: 'kubernetes/'
        ENVIRONMENT:
            description: 'Environment name for deployment'
            required: true
            type: string
            default: 'development'
    secrets:
      KUBECONFIG:
        required: true
      MONGO_PASSWORD:
        required: true

jobs:
    reuse-deployment:
        environment:
          name: ${{ inputs.ENVIRONMENT }}
          url: http://${{ steps.set-ingress-host.outputs.APP_INGRESS_HOST }}
        outputs:
          APP_INGRESS_URL: ${{ steps.set-ingress-host.outputs.APP_INGRESS_HOST }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v7

        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: ${{ inputs.KUBECTL-VERSION }}

        - name: Setup Kubeconfig
          uses: azure/k8s-set-context@v3
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: Fetch K8s Cluster Details
          run: |
            kubectl version
            echo "------------------------------"
            kubectl get nodes

        - name: Save Ingress IP to Environment Variable as Github Environment Variable
          run: |
            echo "INGRESS_IP=141.148.175.20" >> $GITHUB_ENV

        - name: Replace Token in Deployment YAML
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["${{ inputs.K8S-MENIFEST-DIR }}/*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check Deployment YAML
          run: |
            cat ${{ inputs.K8S-MENIFEST-DIR }}/deployment.yaml
            echo "------------------------------"
            cat ${{ inputs.K8S-MENIFEST-DIR }}/service.yaml
            echo "------------------------------"
            cat ${{ inputs.K8S-MENIFEST-DIR }}/ingress.yaml

        - name: Create MongoDB Secret in Kubernetes
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI="${{ inputs.MONGO_URI }}" \
              --from-literal=MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
              --from-literal=MONGO_PASSWORD="${{ secrets.MONGO_PASSWORD }}" \
              --save-config \
              --dry-run=client -o yaml | kubectl apply -f -

        - name: Deploy to Development Environment
          run: |
            kubectl apply -f ${{ inputs.K8S-MENIFEST-DIR }}/deployment.yaml
            kubectl apply -f ${{ inputs.K8S-MENIFEST-DIR }}/service.yaml
            kubectl apply -f ${{ inputs.K8S-MENIFEST-DIR }}/ingress.yaml

        - name: Wait for Deployment to be Ready
          run: |
            kubectl -n ${{ vars.NAMESPACE }} rollout status deployment/solar-system --timeout=120s

        - name: Set App Ingress Host URL
          id: set-ingress-host
          run: |
            APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ing -o jsonpath='{.items[0].spec.rules[0].host}')
            echo "APP_INGRESS_HOST=$APP_INGRESS_HOST" >> "$GITHUB_OUTPUT"
            echo "APP_INGRESS_HOST: $APP_INGRESS_HOST"
